name: Artifacts

on: [push]

jobs:
  create_artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Archive Canary
        uses: actions/upload-artifact@v4
        with:
          name: Archive_Canary
          path: canary_aws